# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  AWS_ACCOUNT_ID : '659441282798'
  ECR_REPOSITORY : 'repo1'
  imageName : abcabc

jobs:
- job: BuildAndPushToECR
  steps:
  - task: Docker@2
    displayName: Build Docker image
    inputs:
      repository: $(imageName)
      command: build
      dockerfile: $(Build.SourcesDirectory)/Dockerfile
      tags: |
        $(tag)
       
  
  - script: |
      # Log in to AWS ECR using the AWS CLI
      docker images
      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.us-east-1.amazonaws.com
    displayName: Log in to ECR
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: $(AwsAccessKey)
      AWS_SECRET_ACCESS_KEY: $(AwsSecretKey)
  
  - script: |
      # Tag the Docker image with ECR repository and dynamically changing tag
      docker tag $(imageName):$(tag)  $(imageName):$(tag)
    displayName: Tag Docker image for ECR
  
  - script: |
      # Push the Docker image to AWS ECR
      docker push $(imageName):$(tag)
    displayName: Push Docker image to ECR
