# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'aws ecr'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AWS Credential1'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        #sourceImageName: 'azurenodejsapp'
        repositoryName: 'repo1'
